version: 2.1

orbs:
  android: circleci/android@2.0.0

jobs:
  unit-test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.12.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache
      - android/save-build-cache
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  android-test:
    parameters:
      system-image:
        type: string
        default: system-images;android-30;google_apis;x86
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.12.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: << parameters.system-image >>
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/outputs/androidTest-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  lint-kotlin:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.12.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Lint Kotlin files
          command: |
            ./gradlew lintKotlin
  release-build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.12.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk
  debug-build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.12.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble debug build
          command: |
            ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug-unsigned.apk
      - android/save-gradle-cache
      - android/save-build-cache
  upgrade-dependencies:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.12.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7a:74:c1:91:81:cc:3a:7e:71:8c:a8:74:01:2a:9d:07"
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Git set upstream branch
          command: |
            git branch --set-upstream-to=origin/main main
      - run:
          name: Upgrade dependencies
          command: |
            ./gradlew upgradeDependencies

workflows:
  test-and-build:
    jobs:
      - lint-kotlin
      - debug-build
      - unit-test:
          requires:
            - debug-build
      - android/run-ui-tests:
          requires:
            - debug-build
          filters:
            branches:
              ignore: main # regular commits
          executor:
            name: android/android-machine
            resource-class: large
            tag: 2021.12.1
      - android-test:
          requires:
            - debug-build
          matrix:
            alias: android-test-all
            parameters:
              system-image:
                - system-images;android-30;google_apis;x86
                - system-images;android-26;google_apis;x86
          name: android-test-<<matrix.system-image>>
          filters:
            branches:
              only: main # Commits to main branch
      - release-build:
          requires:
            - unit-test
            - android-test-all
          filters:
            branches:
              only: main # Commits to main branch
  - nightly:
      triggers:
        - schedule:
            cron: "0 12 * * *"
            filters:
              branches:
                only:
                  -main
      jobs:
        - upgrade-dependencies
