object Deps {
    const val HILT_COMPILER = "com.google.dagger:hilt-compiler:2.43.2"
    const val HILT_ANDROID = "com.google.dagger:hilt-android:2.43.2"
    const val HILT_ANDROID_TESTING = "com.google.dagger:hilt-android-testing:2.43.2"
    const val LIFECYCLE_VIEWMODEL_COMPOSE =
        "androidx.lifecycle:lifecycle-viewmodel-compose:2.5.1"
    const val LIFECYCLE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1"
    const val LIFECYCLE_RUNTIME = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
    const val HILT_NAVIGATION_COMPOSE = "androidx.hilt:hilt-navigation-compose:1.0.0"
    const val ANDROIDX_CORE = "androidx.core:core-ktx:1.8.0"
    const val ANDROIDX_APPCOMPAT = "androidx.appcompat:appcompat:1.5.0"
    const val KOTLINX_COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"
    const val JUNIT = "junit:junit:4.13.2"
    const val ANDROIDX_TEST_EXT = "androidx.test.ext:junit:1.1.3"
    const val ANDROIDX_TEST_ESPRESSO = "androidx.test.espresso:espresso-core:3.4.0"
    const val COMPOSE_UI = "androidx.compose.ui:ui:1.2.1"
    const val ANDROIDX_SECURITY_CRYPTO = "androidx.security:security-crypto:1.0.0"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:2.9.0"
    const val RETROFIT_JACKSON_CONVERTER = "com.squareup.retrofit2:converter-jackson:2.9.0"
    const val JACKSON_MODULE_KOTLIN = "com.fasterxml.jackson.module:jackson-module-kotlin:2.13.3"
    const val JACKSON_ANNOTATIONS = "com.fasterxml.jackson.core:jackson-annotations:2.13.3"
    const val OKHTTP = "com.squareup.okhttp3:okhttp:4.10.0"
    const val OKHTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor:4.10.0"
    const val MATERIAL = "com.google.android.material:material:1.6.1"
    const val COMPOSE_MATERIAL = "androidx.compose.material:material:1.2.1"
    const val COMPOSE_UI_TOOLING_PREVIEW = "androidx.compose.ui:ui-tooling-preview:1.2.1"
    const val COMPOSE_UI_TOOLING = "androidx.compose.ui:ui-tooling:1.2.1"
    const val ANDROIDX_NAVIGATION_COMPOSE = "androidx.navigation:navigation-compose:2.5.2"
    const val ANDROIDX_ACTIVITY_COMPOSE = "androidx.activity:activity-compose:1.5.1"
    const val COMPOSE_UI_TEST_JUNIT4 = "androidx.compose.ui:ui-test-junit4:1.2.1"
    const val ANDROID_GRADLE_PLUGIN = "com.android.tools.build:gradle:7.2.2"
    const val KOTLIN_GRADLE_PLUGIN = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10"
    const val HILT_ANDROID_GRADLE_PLUGIN = "com.google.dagger:hilt-android-gradle-plugin:2.43.2"
    const val KOTLINTER_GRADLE_PLUGIN = "org.jmailen.gradle:kotlinter-gradle:3.11.1"
    const val ROOM_RUNTIME = "androidx.room:room-runtime:2.4.3"
    const val ROOM_PAGING = "androidx.room:room-paging:2.4.3"
    const val ROOM_COMPILER = "androidx.room:room-compiler:2.4.3"
    const val ROOM_KOTLIN = "androidx.room:room-ktx:2.4.3"
    const val ROOM_TESTING = "androidx.room:room-testing:2.4.3"
    const val APP_AUTH = "net.openid:appauth:0.11.1"
    const val ACCOMPANIST_NAVIGATION_MATERIAL =
        "com.google.accompanist:accompanist-navigation-material:0.25.1"
    const val COIL = "io.coil-kt:coil:2.2.0"
    const val COIL_COMPOSE = "io.coil-kt:coil-compose:2.2.0"
    const val COMMONS_TEXT = "org.apache.commons:commons-text:1.9"
    const val PAGING_RUNTIME = "androidx.paging:paging-runtime:3.1.1"
    const val PAGING_COMPOSE = "androidx.paging:paging-compose:1.0.0-alpha14"
    const val KOTLIN_RESULT = "com.michael-bull.kotlin-result:kotlin-result:1.1.16"
    const val ANDROIDX_BROWSER = "androidx.browser:browser:1.4.0"
    const val PRETTY_TIME = "org.ocpsoft.prettytime:prettytime:5.0.3.Final"
    const val COMMONMARK = "org.commonmark:commonmark:0.19.0"
    const val COMMONMARK_EXT_AUTOLINK = "org.commonmark:commonmark-ext-autolink:0.19.0"
    const val SEMVER = "net.thauvin.erik.gradle:semver:1.0.4"
    const val GOOGLE_SERVICES_PLUGIN = "com.google.gms:google-services:4.3.13"
    const val FIREBASE_BOM = "com.google.firebase:firebase-bom:30.3.2"
    const val FIREBASE_ANALYTICS = "com.google.firebase:firebase-analytics-ktx"
    const val FIREBASE_CRASHLYTICS = "com.google.firebase:firebase-crashlytics-ktx"
    const val FIREBASE_CRASHLYTICS_GRADLE_PLUGIN =
        "com.google.firebase:firebase-crashlytics-gradle:2.9.1"
    const val ACCOMPANIST_SWIPE_REFRESH = "com.google.accompanist:accompanist-swiperefresh:0.25.1"
    const val EXOPLAYER = "com.google.android.exoplayer:exoplayer:2.18.1"
    const val KOTLINX_SERIALIZATION_GRADLE_PLUGIN =
        "org.jetbrains.kotlin:kotlin-serialization:1.7.10"
    const val KOTLINX_SERIALIZATION_JSON = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.0"
    const val ANDROID_YOUTUBE_PLAYER = "com.pierfrancescosoffritti.androidyoutubeplayer:core:11.1.0"
    const val ACCOMPANIST_PAGER = "com.google.accompanist:accompanist-pager:0.25.1"
    const val ACCOMPANIST_PAGER_INDICATORS = "com.google.accompanist:accompanist-pager-indicators:0.25.1"
}
